resources:
  repositories:
    - repository: templates
      type: github
      name: NSLS-II/profile-collection-ci
      ref: refs/heads/enh-better-message-on-download-failure
      endpoint: github

jobs:
  - template: nsls2-collection-2021-3.1-py37.yml@templates
    parameters:
      beamline_acronym: XFP
  - template: nsls2-collection-2021-3.1-py39.yml@templates
    parameters:
      beamline_acronym: XFP
